services:
  postgres-db:
    image: postgres:16-alpine
    container_name: estudos-postgres
    environment:
      POSTGRES_USER: miguelsousa
      POSTGRES_PASSWORD: your_password_here
      POSTGRES_DB: couple_schedule_db
    ports:
      - "5433:5432"
    healthcheck: # Garante que o DB está pronto antes da API conectar
      test: ["CMD-SHELL", "pg_isready -U miguelsousa -d couple_schedule_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - estudos-network

  redis-cache:
    image: redis:7-alpine
    container_name: estudos-redis
    ports:
      - "6379:6379"
    networks:
      - estudos-network

networks:
  estudos-network:
    driver: bridge

volumes:
  postgres_data: